[project]
name = "dataclocklib"
description = "Dataclock charts using matplotlib."
authors = [{name = "Andrew Ridyard", email = "developer.surface832@passmail.com"}]
maintainers = [{name = "Andrew Ridyard", email = "developer.surface832@passmail.com"}]
dynamic = ["version"]
license = "GPL-3.0-or-later"
license-files = ["LICENSE", "COPYRIGHT"]
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.11"
classifiers=[
    # 3 - Alpha | 4 - Beta | 5 - Production/Stable
    "Development Status :: 5 - Production/Stable",
    "Framework :: Matplotlib",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = ["matplotlib", "dataclock", "visualisation", "analysis"]
dependencies = [
    "matplotlib",
    "pandas[parquet]>=3.0",
    "pypalettes>=0.1.5",
]

[dependency-groups]
dev = [
    "bump-my-version>=0.28.3",
    "pandas-stubs>=3.0",
    "pkgdx>=0.3.0",
    "pytest>=8.3.3",
    "pytest-cov>=6.0.0",
    "pytest-mpl",
]

[project.optional-dependencies]
docs = [
    "sphinx>=8.1.3",
    "sphinx-autobuild>=2024.10.3",
    "sphinx-rtd-theme>=3.0.2",
    "myst-nb>=1.1.2",
]

[project.urls]
Repository = "https://github.com/andyrids/dataclocklib"
Issues = "https://github.com/andyrids/dataclocklib/issues"
Documentation = "https://andyrids.github.io/dataclocklib/"
Changelog = "https://github.com/andyrids/dataclocklib/blob/main/CHANGELOG.md"

[[tool.uv.index]]
name = "gitlab"
url = "https://gitlab.com/api/v4/projects/82928123/packages/pypi/simple"
explicit = true

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
tmp_path_retention_count = 1
tmp_path_retention_policy = "failed"

[tool.bumpversion]
current_version = "0.2.0"
commit = true
commit_args = "--no-verify"
tag = true
tag_name = "v{new_version}"
tag_message = "chore: tag version update {current_version} -> {new_version}."
allow_dirty = false
message = "chore: version update {current_version} -> {new_version}."

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"
version_scheme = "guess-next-dev"

[tool.hatch.build.targets.wheel]
packages = ["src/dataclocklib"]

[tool.hatch.build.targets.sdist]
include = ["/src", "/README.md", "/CHANGELOG.md"]

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { git = { commit = true, tags = true } }]

[tool.uv.sources]
pkgdx = { index = "gitlab" }
